### ISSUE TITLE
Letsencrypt is broken in the newest release

### ISSUE THREAD

**Issue by j0rg3ns3n** [swizzin/swizzin#742]
### What happened?

Letencrypt script is broken in the newest release. Ive tried the fix here, but still facing the same issue: https://github.com/swizzin/swizzin/issues/10

**Steps to reproduce:** Fresh Install Ubuntu server 20.04 amd64, then Install Swizzin with the following command: "sudo -H su -c 'bash <(wget -qO - git.io/swizzin)'", select to install at least: nginx, panel, rtorrent, rutorrent, and autodl. You can choose to install Letsencrypt during the installation, or after, same error occurs 

Expected results:
I excpected the certificate to be installed with no problems

### Swizzin commit

6f07eb7

### What OS are you using?

Ubuntu 20.04 (Focal)

### What architecture is your OS?

amd64

### Relevant logs and output

```plaintext
**Error**
ERROR   Certificate could not be issued.
Please consult the above and/or check the log (less -R +G /root/logs/swizzin.log)

**Log**
[Wed 18 Aug 2021 12:18:02 PM UTC] Changed default CA to: https://acme-v02.api.letsencrypt.org/directory
[Wed Aug 18 12:18:02] ...       Registering certificates
[Wed 18 Aug 2021 12:18:03 PM UTC] Using CA: https://acme-v02.api.letsencrypt.org/directory
[Wed 18 Aug 2021 12:18:03 PM UTC] Creating domain key
[Wed 18 Aug 2021 12:18:03 PM UTC] The domain key is here: /root/.acme.sh/XXXX.tld/XXXX.tld.key
[Wed 18 Aug 2021 12:18:03 PM UTC] Single domain='XXXX.tld'
[Wed 18 Aug 2021 12:18:03 PM UTC] Getting domain auth token for each domain
[Wed 18 Aug 2021 12:18:06 PM UTC] Getting webroot for domain='XXXX.tld'
[Wed 18 Aug 2021 12:18:07 PM UTC] Verifying: XXXX.tld
[Wed 18 Aug 2021 12:18:07 PM UTC] Nginx mode for domain:XXXX.tld
[Wed 18 Aug 2021 12:18:07 PM UTC] Can not find conf file for domain XXXX.tld
[Wed 18 Aug 2021 12:18:07 PM UTC] Please add '--debug' or '--log' to check more details.
[Wed 18 Aug 2021 12:18:07 PM UTC] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
[Wed Aug 18 12:18:07] ERROR     Certificate could not be issued.
[Wed Aug 18 12:18:07]   Please consult the above and/or check the log (less -R +G /root/logs/swizzin.log)
```

**Comment by liaralabs** [comment]
The issue lies upstream:

https://github.com/acmesh-official/acme.sh/issues/3648

Currently there is nothing to do but wait for the dev to fix the issue there. If you require an SSL certificate now, there should be enough information in that issue for you to work around the issue as it's just an issue with pattern matching and grep on a single line.

If this goes on much longer, a new SSL deployment method may be looked into.

**Comment by j0rg3ns3n** [comment]
Thank you very much. Removing the + from line 3164 and 3166, in /root/.acme.sh/acme.sh solves the issue

**Comment by liaralabs** [comment]
Just checking in. Yes, let's encrypt (acme.sh) is still broken with nginx; however, it is fixed in develop. If folks need an easy way to issue a cert, you can install the dev branch. You have two options that don't involve mucking with code yourself:
```
#LE not yet installed (make sure you 'sudo su -')
curl https://get.acme.sh | BRANCH=dev sh
#LE already failed to run
BRANCH=dev /root/.acme.sh/acme.sh --upgrade
```
Then re-run box install letsencrypt

**Comment by liaralabs** [comment]
Fixed upstream and in production.

**Comment by jpwhale** [comment]
I'm still having this issue. The dev-branch fix also didn't work. Anything I can do?

**Comment by cheeye** [comment]
i have the same issue even with the dev-branch code.
